name: Docker Push CI

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ${{ vars.DOCKER_REGISTRY }}/openrepl

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 7

    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Display env vars
      run: |
        echo "DOCKER_REGISTRY:" ${{ vars.DOCKER_REGISTRY }} 
        echo "sha: " ${{ env.SHA }}
      
    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.SHA }}

    - name: Update the `latest` tag (optional)
      if: success()
      run: |
        docker tag ${{ env.IMAGE_NAME }}:${{ env.SHA }} \
        ${{ env.IMAGE_NAME }}:latest

        docker push ${{ env.IMAGE_NAME }}:latest
