name: Docker Push CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]

env:
  DOCKER_REGISTRY: vickeykumar
  IMAGE_NAME: openrepl

jobs:
  build:
    runs-on: ubuntu-latest

    - name: Display env vars
      run: echo "DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - uses: benjlevesque/short-sha@v2.1
      id: short-sha
      with:
        length: 7
    - run: echo $SHA
      env: 
        DOCKER_SHA: ${{ steps.short-sha.outputs.sha }}

    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_SHA }}

    - name: Update the `latest` tag (optional)
      if: success()
      run: |
        docker tag ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_SHA }} \
        ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

        docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
